### ISSUE TITLE
Sensor can publish dive data to firebase app

### ISSUE THREAD

**Issue by brendanwalters** [project-hermes/hermes-sensor#24]
See https://github.com/project-hermes/hermes-firebase/issues/15

3 topics, 3 functions on sensor for firebase responses:
1) Sensor: publish `createDive(char format, int sensorDiveId, float latStart, longStart, latEnd, longEnd, int sampleCount, timestamp epochStart, epochEnd)`
  - Firebase generates new Dive document with ID firebaseDiveId (hash of properties to tolerate repeat? If not, on repeat we get two partial dives and retry)
  - Firebase: poke sensor with `readyToReceive(string firebaseDiveId, int sensorDiveId)`
2) Sensor: loop publish `diveAppend(char format, int sensorDiveId, timestamp firstDataTime, 41x6byte(depth,temp1,temp2))`
  - Firebase determines firebaseDiveId of "active" dive to which to append via one of three options:
    - stores both sensorDiveId and firebaseDiveId as "lastDiveId_sensor" and "lastDiveId_firebase" on the Sensor object, which it Gets
    - queries Dives that are children of this Sensor for most recent LastUpdatedAt or LastCreatedAt, uses that one (and still verifies sensorDiveId match); this avoids storing state on the Sensor
    - change message formate above: sensor sends full firebaseDiveId per packet (high overhead)
3) Sensor: with tuned backoff, publish `diveDone(char format, int sensorDiveId, string firebaseDiveId)`
  - Firebase: count Data collection under active Dive: if == Dive.sampleCount, poke sensor with `diveComplete(string firebaseDiveId, int sensorDiveId)`
    -- non-response is "not done"

if Firebase ever errors, log error info under errorId, poke sensor with `stopSending(string firebaseDiveId, int sensorDiveId, string errorId)`
  - if we receive enough of these or otherwise have to resend 3 times
  - Sensor: emergency REST dump dive to raw-dive-dump endpoint for manual debugging and data recovery

**Comment by brendanwalters** [comment]
format 'B':

createDive:
 - sprintf(buffer, "%c%d %f %f %f %f %d %d %d", <fields below>)
 1. 'B'
 1. sensorDiveId
 1. latStart
 1. longStart 
 1. latEnd
 1. longEnd,
 1. sampleCount
 1. timeStart
 1. timeEnd


append:
 1. byte[1] = 'B'
 1. byte[1] = (char)sensorDiveId
 1. byte[4] = timestamp (unix epoch, seconds)
 1. byte[1] = (char)sampleCount // can only fit 41
 1. byte[sampleCount][6] = dataPoint[sampleCount]

dataPoint:
 1. byte[2] = (short)depth // cm, good to 327m, negative values fail sanity check
 1. byte[2] = (short)floor(temp1*200) // precision 0.005, range -163 to +163
 1. byte[2] = (short)floor(temp2*200) // precision 0.005, range -163 to +163

**Comment by sonyccd** [comment]
😮 this might take a second to look through

**Comment by sonyccd** [comment]
@brendanwalters Is that the index of the byte or the size of the array?

**Comment by brendanwalters** [comment]
Example messages:
createDive:
`B42 37.939722 22.396944 40.816667 14.433333 30 317246400 317246430`
appendDive:
`QirAy-gSHgoAECc8KB4AaCl0JzIAwCusJkYAGC7kJVoAcDAcJW4AyDJUJIIAIDWMI5YAeDfEIqoA0Dn8Ib4AKDw0IdIAgD5sIOYA2ECkH_oAMEPcHg4BiEUUHiIB4EdMHSIBOEqEHA4BkEy8G_oA6E70GuYAQFEsGtIAmFNkGb4A8FWcGKoASFjUF5YAoFoMF4IA-FxEFm4AUF98FVoAqGG0FEYAAGTsEzIAWGYkEx4AsGhcEgoACGuUEQ==`

^ Dive data:
 - 30 samples,
 - starts at 317246400
 - goes from depth 10 to 290 (2 samples at 290), then back to 10, moving 20cm at a time
 - temp1 starts at 0 and goes up 3 degrees per sample
 - temp2 starts at 1.5 and goes down 1 degrees per sample
```10 0.0 1.5
30 3.0 0.5
50 6.0 -0.5
70 9.0 -1.5
90 12.0 -2.5
110 15.0 -3.5
130 18.0 -4.5
150 21.0 -5.5
170 24.0 -6.5
190 27.0 -7.5
210 30.0 -8.5
230 33.0 -9.5
250 36.0 -10.5
270 39.0 -11.5
290 42.0 -12.5
290 45.0 -13.5
270 48.0 -14.5
250 51.0 -15.5
230 54.0 -16.5
210 57.0 -17.5
190 60.0 -18.5
170 63.0 -19.5
150 66.0 -20.5
130 69.0 -21.5
110 72.0 -22.5
90 75.0 -23.5
70 78.0 -24.5
50 81.0 -25.5
30 84.0 -26.5
10 87.0 -27.5
```

**Comment by brendanwalters** [comment]
A quick go script to generate the above test data (or edit to get other test data):
https://play.golang.org/p/W1O57QUEOyH

**Comment by brendanwalters** [comment]
Correction: the data will have to be base85 encoded in addition to the above because contrary to some of the documentation / help threads, Particle.publish() does NOT support all char values, failing on at least 0x00 and some high char values. Verified in tests.

See
https://community.particle.io/t/how-to-publish-binary-data/36142/2
https://community.particle.io/t/utf-8-ascii-encoding-decoding-solved/25815/5
